In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn imports metrics 
from sklearn.metrics import r2_score


def Build_Data_Set():
    data = pd.read_excel("G:/Gzb/Ugzb.xlsx")
    feat = ['Year', 'Wdf' , 'T','Cloud']
    x = data[feat]
 
    tar = np.array(data['Jun-Sep'])
    y = pd.Series(tar)
    return x,y

def Analysis():
    x,y = Build_Data_Set()
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=1)
    from sklearn.linear_model import LinearRegression

    lreg = LinearRegression()
    lreg.fit(x_train, y_train )
    ypred = lreg.predict(x_test)
    print(lreg.intercept_)
    print(lreg.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))

    
Analysis()


4004.32983717
[  0.27570408  -2.41724744 -45.46312238   5.08337824]
0.630999453042
84.0701126205
11681.2290163
108.079734531


In [4]:
def Build_Cloud():
    cloud_data = pd.read_excel("G:/Gzb/Ugzb.xlsx")
    x = cloud_data[['Year']]
    y = cloud_data[['Cloud']]
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=10)
    from sklearn.linear_model import LinearRegression
    cldreg = LinearRegression()
    cldreg.fit(x_train, y_train )
    ypred = cldreg.predict(x_test)
    print(cldreg.intercept_)
    print(cldreg.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))
    yr = float(input("Enter year"))
    c = cldreg.predict(yr)
    print(c)
    print(type(c))

    
    
    

Build_Cloud()
    




[ 153.61962002]
[[ 0.02678417]]
0.0322998452122
7.42152286205
88.8800409828
9.42762117307
Enter year2003
[[ 207.26831507]]
<class 'numpy.ndarray'>


In [5]:
def Wet_Day_Analysis():
    cloud_data = pd.read_excel("G:/Gzb/Ugzb.xlsx")
    x = cloud_data[['Year' ,'T']]
    y = cloud_data[['Wdf']]
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=14)
    from sklearn.linear_model import LinearRegression
    wdfreg = LinearRegression()
    wdfreg.fit(x_train, y_train )
    ypred = wdfreg.predict(x_test)
    print(wdfreg.intercept_)
    print(wdfreg.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))
    
Wet_Day_Analysis()

[ 33.04076346]
[[ -3.23678818e-04   7.31858251e-01]]
0.803180019968
0.951087339162
1.34075495721
1.15790973621


In [6]:
def Temp_Analysis():
    cloud_data = pd.read_excel("G:/Gzb/Ugzb.xlsx")
    x = cloud_data[['Year']]
    y = cloud_data[['T']]
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=None)
    from sklearn.linear_model import LinearRegression
    treg = LinearRegression()
    treg.fit(x_train, y_train )
    ypred = treg.predict(x_test)
    print(treg.intercept_)
    print(treg.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))
    yr = float(input("Enter year"))
    t = treg.predict(yr)
    print(t)
    print(type(t))
    
Temp_Analysis()

[ 142.09757019]
[[-0.019168]]
0.0139696699263
1.99031440635
6.95588967186
2.63740206868
Enter year2003
[[ 103.70407366]]
<class 'numpy.ndarray'>


In [9]:
def Wet_Day_Analysis():
    cloud_data = pd.read_excel("G:/Gzb/Ugzb.xlsx")
    x = cloud_data[['Year']]
    y = cloud_data[['Wdf']]
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=19)
    from sklearn.linear_model import LinearRegression
    wdfreg = LinearRegression()
    wdfreg.fit(x_train, y_train )
    ypred = wdfreg.predict(x_test)
    print(wdfreg.intercept_)
    print(wdfreg.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))
    yr = float(input("Enter year"))
    w = wdfreg.predict(yr)
    print(w)
    print(type(w))
    
Wet_Day_Analysis()

[ 136.50051762]
[[-0.01411423]]
0.106584614671
1.423037347
3.68735352715
1.92024829831
Enter year2003
[[ 108.22971328]]
<class 'numpy.ndarray'>


In [18]:
def Analysis():
    x,y = Build_Data_Set()
    from sklearn.cross_validation import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x ,y ,test_size=20, random_state=1)
    from sklearn.linear_model import LinearRegression

    lreg = LinearRegression()
    z = lreg.fit(x_train, y_train )
    ypred = z.predict(x_test)
    print(z.intercept_)
    print(z.coef_)
    from sklearn.metrics import r2_score
    print(r2_score(y_test, ypred))
    from sklearn import metrics
    print(metrics.mean_absolute_error(y_test , ypred))
    print(metrics.mean_squared_error(y_test , ypred))
    print(np.sqrt(metrics.mean_squared_error(y_test , ypred)))
    return z

def Prediction():
    z = Analysis()
    print(z.coef_)
    print(z.intercept_)
    
    x = np.array([2003 ,108.23 , 103.74 , 207.67])
    
    y = z.predict(x)
    print(y)
    
    
Prediction()


4004.32983717
[  0.27570408  -2.41724744 -45.46312238   5.08337824]
0.630999453042
84.0701126205
11681.2290163
108.079734531
[  0.27570408  -2.41724744 -45.46312238   5.08337824]
4004.32983717
[ 634.26725264]


C:\Users\vaibhav\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
